### ISSUE TITLE
Ensure font size doesn't get out of control on Review page

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-frontend#107]
Could be introduced by #106; keep the review slim and lean

**Comment by ALRubinger** [comment]
Or if doing this proposal is easy and quick:

  https://redhat.invisionapp.com/share/2DBHCI7X9#/screens/231156310

...go for it

**Comment by gastaldi** [comment]
Looks good to me.  @ALRubinger can you try it with the latest master?

**Comment by ALRubinger** [comment]
![screenshot16](https://cloud.githubusercontent.com/assets/199891/25553943/f4c480fe-2c8e-11e7-8abb-9732a1678f90.png)

Close enough until UXD changes are applied. :)
