### ISSUE TITLE
Intro page is not mobile-friendly

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#110]
![tmp_24834-screenshot_20170429-014511324025723](https://cloud.githubusercontent.com/assets/54133/25552956/a96a99b0-2c7d-11e7-9699-868a8dd85cce.png)

![tmp_24834-screenshot_20170429-014527-46802625](https://cloud.githubusercontent.com/assets/54133/25552955/9ea9e9fe-2c7d-11e7-91b2-63c2bd3385fa.png)

**Comment by ALRubinger** [comment]
Worth asking @catrobson if it was designed to be :)

**Comment by catrobson** [comment]
Yes, the button should wrap below the text, and the cards should stack vertically on mobile.  If you follow a standard bootstrap grid for this it should respond quite nicely for that.
