### ISSUE TITLE
Create Early Access announcement and Signup form copy/CTAs

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-frontend#112]
![screenshot2](https://cloud.githubusercontent.com/assets/199891/25560220/49450e86-2d1c-11e7-864b-e1104aadceef.png)
Attached is the current state of launch.openshift.io.

We need to add calls to action to:

* Sign up for Early Access
* Point the public to register for OpenShift Online Starter through the Red Hat Developer Program (links to https://manage.openshift.com)
* Point to the appdev.openshift.io site for community/documentation/Minishift installation instructions

With the short time I have available, it'd be helpful to know exactly the deltas between the attached screenshot and what we need to have.

The file to be edited is: https://github.com/openshiftio/launchpad-frontend/blob/coming-soon/src/app/wizard/intro/intro.component.html.  For anyone looking to make PRs, that'd be very helpful -- note that this file is on the `coming-soon` branch.

For any changes, submit to me to field; they'll get rebased atop `master` in the `coming-soon` branch and never be applied to `master`.

**Comment by ALRubinger** [comment]
Also assigned: @jbalunas

**Comment by jclingan** [comment]
Here is what I've come up with. It is unclear to me if the user needs to sign up for OpenShift Online Starter right away, but I've included it here.

---

Soon you’ll be able to create a modern enterprise application - continuously built and deployed on Red Hat OpenShift Online - in minutes.  [Sign up](https://docs.google.com/forms/d/e/1FAIpQLSe9IcY0TUSdSheW3-33BWs9FsgCYwPXybAuY_kcdexhY_NNTA/viewform?usp=sf_link) for Early Access to launch.openshift.io, and also [sign up](https://manage.openshift.com) for OpenShift Online Starter.

Until then, [install launch.openshift.io](http://appdev.openshift.io/docs) to your desktop for a local experience.

**Comment by balunasj** [comment]
I like the updates John, and have a few adjustments starting after the "in minutes.":

> We’re prepping for launch, and invite you to Sign up for our Early Access program. 
> 
> In the mean time you can prep yourself by signing up for OpenShift Online Starter, and install launch.openshift.io to your desktop for a local development experience.
> 

Also do we need the launch.openshift.io at the top?  The red on black is not ideal, and perhaps not needed.  Or perhaps a restyle but not sure exactly how.

**Comment by ALRubinger** [comment]
Unless I feel strongly about it, I generally leave style that's provided to us from the UXD team (which the red launch.openshift.io was).  We can have some review with Catherine later if we'd like to raise edits.

**Comment by ALRubinger** [comment]
So we now have 3 CTAs:

* Request early access
* Sign up for OpenShift Online Starter
* Head over the docs to install on local Minishift

Relative to the image included in the original posting, how do we prioritize and position these?  One red button for the request form, and the rest in links in the text?  3 red buttons, in some order?

@balunasj  @jclingan

**Comment by balunasj** [comment]
Imo the priority order is how you listed them.  1 red button with request early access, and the other are in text/links.

**Comment by ALRubinger** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/199891/25593921/a7fd316c-2e8c-11e7-84cb-b96261da6bd0.png)

+1s: @balunasj @jclingan

**Comment by balunasj** [comment]
+1 from me and +1 from @jclingan

**Comment by ALRubinger** [comment]
https://launch.openshift.io
