### ISSUE TITLE
buttons overlay mission description

### ISSUE THREAD

**Issue by rdruss** [openshiftio/launchpad-frontend#116]
![button overlay](https://cloud.githubusercontent.com/assets/367748/25762835/92c03a24-319d-11e7-837b-81d0ef113149.png)

In step 2 when choosing a mission, if the mission description field is big enough, the buttons may overlay the text.  See the attached image for an example.

**Comment by gastaldi** [comment]
You mean like https://github.com/openshiftio/launchpad-frontend/issues/114?

**Comment by rdruss** [comment]
Yup, looks like a duplicate.  I'll close this one.
