### ISSUE TITLE
realtime validation on "OpenShift Project name" field

### ISSUE THREAD

**Issue by rdruss** [openshiftio/launchpad-frontend#117]
On the Project Info (4) page, the Next button is not enabled until the "OpenShift Project name" field has been validated.  Validation doesn't happen until focus has moved from the field.  However, given that the "OpenShift Project name" field is the only field that is needed to be entered before hitting next, it may be nice from a workflow perspective to allow validation to happen while the field is being modified to allow the Next button to be enabled without having to move focus.

**Comment by edewit** [comment]
This is what we used to have, on all fields. The trouble is that because the validation is so long it could happen that you loose some of the things you typed while validation is running.

**Comment by rdruss** [comment]
Out of curiosity, why is the Next button disabled before validation?  It looks like validation is run before submission anyway.  I tested that by entering a valid project name, allowing the Next button to be enabled, then changing the project name to something invalid and hitting next.  Validation was before submission with error messages displayed at the top of the page.

**Comment by Ladicek** [comment]
This is somewhat duplicate-ish to #92.

**Comment by rdruss** [comment]
@Ladicek, it is definitely related.  I was just looking for an experience where the developer would just need to fill in the project name and could click Next without having to tab or click off the field first.

**Comment by edewit** [comment]
We used to have this and removed it again because people lost their edits when validation occurred. I've created another implementation of this it might be better now. It's enabled on the "Openshift project name" and the "Github project name" field

**Comment by edewit** [comment]
added real time validation again for this field
