### ISSUE TITLE
Use CSS3 Animations/transitions between steps

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#122]
The "Loading Wizard" message between pages is a bit annoying, looks like a subliminal message is displayed whenever I navigate to the next page.

It would be nice if we used CSS animations between them. For example, when you click *Next* it slides the wizard contents to the left and when click *Previous* to the right, like in a slide deck

**Comment by gastaldi** [comment]
Or just use a fade-out/fade-in animation if that looks better

**Comment by gastaldi** [comment]
Maybe this would help: https://angular.io/docs/ts/latest/guide/animations.html

**Comment by edewit** [comment]
added slide transition, but it's not great maybe everybody likes it then it's fine to merge https://github.com/openshiftio/launchpad-frontend/pull/127
