### ISSUE TITLE
Hard to know how to start the Wizard

### ISSUE THREAD

**Issue by quintesse** [openshiftio/launchpad-frontend#124]
When I go to the first page of the launch page new style:

![image](https://cloud.githubusercontent.com/assets/778793/26063231/b06312b6-398d-11e7-8cec-b1e32667e253.png)

I find it hard to know how to actually start. The 3 boxes at the bottom seems like possible buttons / choices to make. But they aren't. I still lost time investigating them, clicking on them, realizing it was not what I want, go back, etc,

On the other hand the red "Prepare for Takeoff" because of it's style and position doesn't seem to be a button.

Suggestions: a) move the button below the title, b) put a right pointing arrow in the button (eg. "Prepare for Takeoff >>")

**Comment by gastaldi** [comment]
What if we changed the wizard steps like it was proposed in https://github.com/openshiftio/launchpad-addon/issues/26 and started by choosing the runtime?

**Comment by quintesse** [comment]
But that would still be _after_ people see this page, right? I mean, this is "step 0" so to speak, we haven't gotten to the wizard yet.

**Comment by gastaldi** [comment]
IMHO I'd assume that after choosing the runtime in this page, it would automatically navigate to step 2, so the wizard would already have started from the intro page :)

**Comment by gastaldi** [comment]
Regarding your suggestions, I agree with both of them. The button already appears below the title if you have a smaller screen resolution.

**Comment by edewit** [comment]
created new UI with more prominent button
