### ISSUE TITLE
Review page shows explanation instead of value

### ISSUE THREAD

**Issue by quintesse** [openshiftio/launchpad-frontend#129]
If you left the name of the github repo blank in the previous page the review page will show this:

![image](https://cloud.githubusercontent.com/assets/778793/26175198/2640ea2e-3b52-11e7-989d-25585145404b.png)

I think it should show the actual value that will be used ("test" in this case)

**Comment by edewit** [comment]
The front-end is quite stupid ATM, doing this will introduce more knowledge about the actual fields

**Comment by gastaldi** [comment]
I think it makes sense in this specific case, as this step is not part of the backend specifically and will be more user-friendly.

**Comment by edewit** [comment]
done
