### ISSUE TITLE
Be resilient for other service failures

### ISSUE THREAD

**Issue by SlavoKrupa** [openshiftio/launchpad-frontend#138]
Just a minor thing that can be considered, because if I run the launchpad locally I can access frontend, when the backend is not yet deployed. Maybe we can consider retrieving/checking status of other services before accessing them? Or maybe we can use some Circuit Breakers for the access of other services (because otherwise wizards is stuck)

**Comment by edewit** [comment]
it now retries 3 times before it fails, user can reload manually to try again
