### ISSUE TITLE
Step 5: Guide name variable not replaced by actual guide name 

### ISSUE THREAD

**Issue by inoxx03** [openshiftio/launchpad-frontend#150]
Please see picture for reference:
![launcher-latest-step5-variable-issue](https://user-images.githubusercontent.com/17914654/28468368-0ee92346-6e33-11e7-853e-0ebe68b64c31.png)

To replicate:
1. Deploy latest Launcher version to Minishift
2. Select _Deploy to OpenShift Online_
3. Select any of the Missions and Runtimes.
4. Upon reaching the Review screen (Step 5), the docs snippet should contain a link with a guide name procedurally generated based on the selected runtime and mission. This does not happen and the link text remains rendered as `{guideName}`.

**Comment by edewit** [comment]
The front-end docs where downloaded and converted to html at build time. Converting to html is now done at [runtime](https://github.com/openshiftio/launchpad-frontend/pull/155) and users selection is added as asciidoc variables when converting to html. So no need to add this: https://github.com/openshiftio/appdev-documentation/pull/411

https://github.com/openshiftio/launchpad-frontend/pull/155
