### ISSUE TITLE
guideName and guideURL variables are not set in the Review page when choosing Node.js runtime

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#156]
![screenshot from 2017-08-03 18-36-01](https://user-images.githubusercontent.com/54133/28944877-a3aefbc6-787a-11e7-928e-caacd52d947f.png)

**Comment by edewit** [comment]
@gastaldi this is fixed by https://github.com/openshiftio/launchpad-frontend/pull/155
