### ISSUE TITLE
Remove tooltip to manually set federated identity

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-frontend#162]
![screenshot2](https://user-images.githubusercontent.com/199891/29078827-72926d9a-7c29-11e7-843e-7626ff4e5bb0.png)

@gastaldi can you confirm that for new users, the federated identity setup is automatically orchestrated through the new domain?

**Comment by gastaldi** [comment]
I tested that yesterday and the federated identity setup is *NOT* being automatically orchestrated. I am investigating what is missing

**Comment by ALRubinger** [comment]
@gastaldi Thanks! Mind tracking that somewhere in appdev-planning and setting a dependency here?

**Comment by gastaldi** [comment]
I assigned https://github.com/openshiftio/appdev-planning/issues/26 to myself

**Comment by gastaldi** [comment]
Link should remain as we're using our own realm
