### ISSUE TITLE
Change authentication service when running in launch.openshift.io

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#163]
In order to have federated identities setup with the user first login as described in https://github.com/openshiftio/appdev-planning/issues/26#issuecomment-321066528, we need to change how the authentication is handled in the frontend.

The workflow when the Log In Button is clicked should be: 

-  Redirect the user to https://api.openshift.io/api/login/authorize?link=true&redirect=https://some.endpoint.on.your.side 
-  Eventually it should come back to https://some.endpoint.on.your.side?token=xxx

The token will be available for consumption then.

This is needed before https://github.com/openshiftio/launchpad-frontend/issues/162

@edewit I assigned it to you but feel free to assign it to me back if you feel so

**Comment by edewit** [comment]
We only need to add a redirectUri in the `keycloak.json` like so:

```js
{
  "realm": "",
  "url": "",
  "clientId": "openshiftio-public",
  "redirectUri": "https://api.openshift.io/api/login/authorize"
}
``` 
But what are the realm and url? I'll assign back to you so you can test.

**Comment by gastaldi** [comment]
As I was told by Aslak, there is no need for any Keycloak realm nor url. We just need to access that api.openshift.io URL and that would be it.

**Comment by gastaldi** [comment]
```
GET https://api.openshift.io/api/user
with the header 
"Authorization: Bearer <token>"

**Comment by gastaldi** [comment]
This library does the dirty work for us: https://github.com/fabric8-ui/ngx-login-client and it's already used  across fabric8-ui and fabric8-planner.

**Comment by gastaldi** [comment]
Closing for now as we'll have our own realm
