### ISSUE TITLE
Add a link to the Contribution Guide

### ISSUE THREAD

**Issue by tradej** [openshiftio/launchpad-frontend#164]
Hi, I would like to request adding a link that would lead to `/docs/contrib-guide.html` in the footer of the Launchpad app. I believe "Contributing" or a similar link text would be appropriate. The book is already up at http://appdev.openshift.io/docs/contrib-guide.html, it's just not linked from anywhere. Thank you.

CC @ALRubinger @rhoads-zach.

**Comment by tradej** [comment]
Hi, folks, any update, please?

**Comment by gastaldi** [comment]
I'll work on this.
