### ISSUE TITLE
Update reference to docs topic

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/launchpad-frontend#169]
Currently there is a hard reference to a doc topic:

https://github.com/openshiftio/launchpad-frontend/blob/master/src/assets/adoc.index#L2

this i need to be update to something in the master branch (i.e. not referring to a hash).

**Comment by gastaldi** [comment]
The new reference should be https://raw.githubusercontent.com/openshiftio/appdev-documentation/master/docs/topics/dev-guide-mission-intro.adoc

**Comment by tradej** [comment]
I believe you also need to add https://raw.githubusercontent.com/openshiftio/appdev-documentation/master/docs/topics/templates/document-attributes.adoc to the list because it contains the definitions of attributes that are used in other files.

**Comment by rhoads-zach** [comment]
Thanks @tradej, filed a PR with the old content. We can iterate the content as needed.


https://github.com/openshiftio/appdev-documentation/pull/507
