### ISSUE TITLE
UI should list the available projects

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#175]
The project name can be reused (must be reused when deploying in a starter cluster due to quota constraints).

It would be nice if the `OpenShift Project name` input could list the available projects or allow creating a new one.

**Comment by gastaldi** [comment]
Mission control already supports deploying in an existing project given its name. 

This is necessary for https://github.com/openshiftio/appdev-planning/issues/50

**Comment by edewit** [comment]
PR send: https://github.com/openshiftio/launchpad-frontend/pull/176
