### ISSUE TITLE
Description text is wrong in steps

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#179]
It seems that the description text for every step is shifted one step. The Mission description text is displayed in the Runtime page and the Runtime description text is displayed in the Project Info step.

![pasted image at 2017_09_01 05_58 pm](https://user-images.githubusercontent.com/54133/29991826-938c2c22-8f64-11e7-8d9f-8e1e0488b895.png)

**Comment by edewit** [comment]
off by one fixed in 2b1d53c
