### ISSUE TITLE
Note on runtime selection that node.js is tech preview

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#183]
From the September 11, 2017 demo meeting
![screenshot from 2017-09-11 14-00-42](https://user-images.githubusercontent.com/54133/30286903-9f86fe34-96f9-11e7-9f86-9a6df27f61f9.png)

**Comment by edewit** [comment]
fixed in 28bab1f 
![screenshot from 2017-09-12 14-38-58](https://user-images.githubusercontent.com/51133/30326395-b9e9bcce-97c8-11e7-90e6-af6b8974295f.png)
