### ISSUE TITLE
Prepended user name may introduce special characters

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-frontend#193]
....which are invalid for OpenShift project names

For instance my user name is alr@alrubinger.com:

![screenshot8](https://user-images.githubusercontent.com/199891/30937943-65a6de32-a3a6-11e7-8904-f48e4e0042b4.png)

**Comment by edewit** [comment]
fixed 3e33b823286c19890cb9b67249478523ee639b53
