### ISSUE TITLE
GitHub validation is broken

### ISSUE THREAD

**Issue by quintesse** [openshiftio/launchpad-frontend#194]
The simplest issue is that you can type a name in the "OpenShift Project name" field that is the same as the name of an existing GitHub repository in your account and you won't get any error.

But then it gets a bit weird: if you then change the "OpenShift Project name" to something else you actually get the error you should have had the first time! Changing it back again removed the error.

Is the test inverted perhaps?

**Comment by edewit** [comment]
yep it called validate first and then updated the value... fixed in 81d5a58cfeee9f6a013202306d63513b2d483d85
