### ISSUE TITLE
UX Evaluation & Updates

### ISSUE THREAD

**Issue by catrobson** [openshiftio/launchpad-frontend#31]
Evaluate the current UI against PatternFly, OpenShift, and Fabric8 to ensure consistency of pattern and style usage.

Verification Criteria:
* UI suggestions captured and shared with PatternFly, OpenShift, Fabric8 UX teams for a final check of consistency by many
* Final UI improvements shared back to Obsidian team

**Comment by ALRubinger** [comment]
@edewit is engaging with Jessica as we iterate on the wireframes.  Closing this one in favor of opening new tickets that may be associated with code commits.
