### ISSUE TITLE
UX - Workflows

### ISSUE THREAD

**Issue by catrobson** [openshiftio/launchpad-frontend#32]
UXD to work with Obsidian team to understand use case flows for guiding users through some project setups.

Verification Criteria:
* Meetings with Obsidian team recorded and captured
* Flows discussed captured, documented, shared with Obsidian team in preparation for wireframe phase
* Any outstanding questions documented

**Comment by ALRubinger** [comment]
Closing as we've begun engagement and should handle new issues in actionable tickets :)

Thanks for the support, UXD!
