### ISSUE TITLE
Clicking "Finish" on the Booster selection screen sometimes comes back to the same screen in the wizard

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-frontend#46]
...should be seeing "Launch on OpenShift" and "Download" buttons

**Comment by gastaldi** [comment]
@edewit maybe it's a conflict with /validate and /next? Better wait for validation before proceeding.

**Comment by ALRubinger** [comment]
d332658143a8d8e7287551756c0e0c2dbf38b29a

**Comment by ALRubinger** [comment]
Now this issue is: you have to click "Finish" twice to get to the next screen.  Closer, but not totally there :)
