### ISSUE TITLE
Dynamically pick up KEYCLOAK_URL and KEYCLOAK_REALM values

### ISSUE THREAD

**Issue by quintesse** [openshiftio/launchpad-frontend#55]
Right now as far as I can see these values are hardcoded in https://github.com/openshiftio/launchpad-frontend/blob/master/src/assets/keycloak/keycloak.json ? But they really should be picked up from the environment at **runtime**, just like we do for `BACKEND_URL` and `KEYCLOAK_SKIP`.

We already use `LAUNCHPAD_MISSIONCONTROL_KEYCLOAK_URL` and `LAUNCHPAD_MISSIONCONTROL_KEYCLOAK_REALM` for Mission Control of course, but perhaps we should be consistent and add `LAUNCHPAD_FRONTEND_KEYCLOAK_URL` and `LAUNCHPAD_FRONTEND_KEYCLOAK_REALM` for the frontend? Even if they would always have the same values?

I looked at adding this myself to the `entrypoint.sh` script, but unfortunately it didn't work as I expected so I'm leaving this to you @edewit :)

**Comment by edewit** [comment]
Wouldn't call it hardcode, but configured in a json ;). The reason that it can't do it the same way as `BACKEND_URL` is that keycloak sits on top of http, that way it can add the authentication header transparently, but for it to read settings.json it needs http, so it's a cyclic dependency.

**Comment by edewit** [comment]
Named them `KEYCLOAK_URL` and `KEYCLOAK_REALM`, @quintesse as they need to be the same to work fixed in 825aa0b

**Comment by quintesse** [comment]
Well I'd still say we should be consistent, because all the container images get their own environment, so they don't share those values anyway. And in that case you could just as well give them different names.

But if you don't want that we should *at least* call them `LAUNCHPAD_KEYCLOAK_XXX` right? And make that change in Mission Control as well. And then we should also rename `BACKEND_URL` to `LAUNCHPAD_FRONTEND_BACKEND_URL` and `KEYCLOAK_SKIP` to `LAUNCHPAD_FRONTEND_KEYCLOAK_SKIP`

Want me to do that?

**Comment by edewit** [comment]
sure, you can do that
