### ISSUE TITLE
No error message displayed if an error occurs during project

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/launchpad-frontend#66]
No error message is displayed if something happens during the creation of the project

![screenshot 2017-04-11 14 30 23](https://cloud.githubusercontent.com/assets/463790/24909407/0c8d5270-1ec4-11e7-8dc8-e96633ffa94c.png)

Such situation can occur if :  
- We use as project name an existing github repo name
- We use as project name an existing openshift namespace/project

**Comment by gastaldi** [comment]
Resolved with the status messages feature
