### ISSUE TITLE
Transient or platform-specific: not showing link under GitHub repo created

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-frontend#69]
@jclingan has a screenshot: 
![launchpad](https://cloud.githubusercontent.com/assets/199891/25058756/0ae7bd00-214b-11e7-8cf4-a9b785a9d895.png)

**Comment by edewit** [comment]
it could be that you missed the notification

**Comment by gastaldi** [comment]
I think we may need to buffer StatusMessageEvents until the Websocket session is opened. Let me try to reproduce this

**Comment by gastaldi** [comment]
Fixed in https://github.com/openshiftio/launchpad-missioncontrol/issues/236
