### ISSUE TITLE
Deploy on Openshift ignores any choices made previously after Sign-In button is pressed

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#71]

**Comment by edewit** [comment]
should be fixed now the state is stored in the url `wizard/launchpad-new-project/3/<encoded-state>`

**Comment by ALRubinger** [comment]
I think this might be fixed, but let's be sure when we re-enable auth.

**Comment by gastaldi** [comment]
It is fixed. Good job!
