### ISSUE TITLE
The last page of the launchpad workflow has no link to the home page

### ISSUE THREAD

**Issue by RadekKoubsky** [openshiftio/launchpad-frontend#75]
When I finish the launchpad workflow and succesfully deploy the app, for instance via the "Launch on OpenShift" button, I want to go back to the home page, but there is no way to do it from the last page. The Red Hat OPENSHIFT.io logo in the upper-left corner could point to home page, or there could be "Home" button or something similar. What do you think?

**Comment by edewit** [comment]
https://github.com/openshiftio/launchpad-frontend/pull/74 introduces a `restart` button

**Comment by RadekKoubsky** [comment]
Ok, cool:)

**Comment by edewit** [comment]
added logo click in 1843a0bacd842c0bc9f69bc9c87ff59200616023

**Comment by gastaldi** [comment]
Can this issue be closed?

**Comment by RadekKoubsky** [comment]
Verified the logo click and the back/restart button, for me is ok. @SlavoKrupa WDYT?

**Comment by SlavoKrupa** [comment]
@gastaldi yes.
