### ISSUE TITLE
Inconsistency after selecting runtime

### ISSUE THREAD

**Issue by rdruss** [openshiftio/launchpad-frontend#79]
![launch issue](https://cloud.githubusercontent.com/assets/367748/25245333/4f147bd8-25c1-11e7-8577-463cc585c2d2.png)

The text says you can either download a zip or launch on openshift, but you *cannot* download a zip from this screen.

**Comment by gastaldi** [comment]
It now displays the following if Open in Openshift is chosen: 
```
Your project is ready; now you can launch it on OpenShift Online.

The launch process will create both a GitHub repository containing your new Booster and a new project on OpenShift Online to automatically build and deploy the codebase.
```

And if ZIP is chosen
```
Your project is ready; now you can download it to build and deploy locally.
```
