### ISSUE TITLE
Adapt frontend to backend changes

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#80]
The backend now implements the same flow that was implemented locally in the frontend. 
By consequence, the frontend master no longer works appropriately, unless https://github.com/openshiftio/launchpad-frontend/commit/958d1b104f1467ef0635741b881b8ece1463a083 is reverted

**Comment by edewit** [comment]
fixed by https://github.com/openshiftio/launchpad-frontend/pull/86
