### ISSUE TITLE
Make "Registration" button take proper action

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-frontend#83]
Pending PR #82 

The registration button needs to:

1) Start the registration flow to OpenShift Online Starter through RHD
2) Be linked into Segment tracking to track the action (Step 3 of https://segment.com/docs/sources/website/analytics.js/quickstart/)

**Comment by ALRubinger** [comment]
PR #82 done, ready for this to be scheduled.

**Comment by gastaldi** [comment]
I think this can be closed?
