### ISSUE TITLE
Blank screen on frontend root when not using Keycloak auth

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-frontend#90]
![screenshot3](https://cloud.githubusercontent.com/assets/199891/25418064/e5530c96-2a16-11e7-932c-ee5774795c2e.png)

**Comment by edewit** [comment]
fixed in 6b4c623b11198b94c956b23a06cb7d7264a576ab now prints "Fake User" when keycloak is set to be skipped
