### ISSUE TITLE
what happens if I click the "Launch on OpenShift" button again?

### ISSUE THREAD

**Issue by Ladicek** [openshiftio/launchpad-frontend#91]
Say I go through the entire wizard, using the Continous Delivery option, and then successfully launch the booster on OpenShift. Once the process finishes, the "Launch on OpenShift" button is enabled again. What happes if I click it second time? Not sure if that should even be possible; the button should probably stay disabled. At least in case of success -- in case of errors, I can see the value of another attempt that might succeed in certain cases.

**Comment by edewit** [comment]
fixed "Launch on OpenShift" button now remains disabled
