### ISSUE TITLE
need to click "Next" twice on the "Metadata" step of the wizard

### ISSUE THREAD

**Issue by Ladicek** [openshiftio/launchpad-frontend#92]
Say I go through the wizard successfully, using the Continuous Deployment option, and on the last step, "Metadata", I fill all the empty inputs, but won't get out of the form by a Tab key or clicking in the blank to trigger validation -- instead, I click the "Next" button right after filling an empty input, so the click triggers the `change` event, which triggers validation. Validation succeeds, and then I need to click "Next" again.

**Comment by edewit** [comment]
Now validation begins after 1.5 seconds of not typing. If you are fast and click on next before validation is started you'll still have to click twice, but no idea how we could "fix" that. Have a look at how it responds now and if you have any other suggestions just add them here.

**Comment by Ladicek** [comment]
I think it works much better in this regard.
