### ISSUE TITLE
Form validation javascript in wizard steps

### ISSUE THREAD

**Issue by RadekKoubsky** [openshiftio/launchpad-frontend#93]
When clicking on a runtime icon in Runtime step of the Wizzard, it fires "Validating form" javascript. Same in Mission step while clicking on radio buttons.
see screenshot 
![validator-runtime-step](https://cloud.githubusercontent.com/assets/2538092/25436076/731a2584-2a92-11e7-8b64-a0c206722afc.png)

**Comment by RadekKoubsky** [comment]
Overall the layout is broken when you are moving between wizard steps. This definitely need a revision.

**Comment by edewit** [comment]
could you elaborate what "overall broken" means

**Comment by RadekKoubsky** [comment]
When you click on a runtime icon, it also shows two scroll panels (botom, right) and then they dissapear, see in the screenshot. At the same time, the "Next" button is greyed out. I will be testing launcher today, will let you know.

**Comment by edewit** [comment]
scrollbars have been fixed

**Comment by edewit** [comment]
no longer validates on the runtime and mission steps
