### ISSUE TITLE
 TypeError: d[(e.state.steps[(e.stepIndex - 1)] + "-intro")] is undefined

### ISSUE THREAD

**Issue by gastaldi** [openshiftio/launchpad-frontend#98]
I see the following error when clicking the Launch on Openshift button:

![screenshot from 2017-04-26 19-17-24](https://cloud.githubusercontent.com/assets/54133/25459536/1d36c8b6-2ab5-11e7-984f-714196f51465.png)

The project is deployed in Openshift and the Github repository is created though

**Comment by edewit** [comment]
How do you reproduce this error I've tried on ff and my local environment

**Comment by gastaldi** [comment]
I just followed the normal steps. Let me see if I can reproduce it again

**Comment by gastaldi** [comment]
Can´t reproduce anymore. Closing
